#!/bin/zsh

cp -ru $HOME/.config/bat ./
cp -ru $HOME/.config/bluetuith ./
cp -ru $HOME/.config/btop ./
cp -ru $HOME/.config/cava ./
cp -ru $HOME/.config/cmus ./
cp -ru $HOME/.config/dconf ./
cp -ru $HOME/.config/dunst ./
cp -ru $HOME/.config/foot ./
cp -ru $HOME/.config/gammastep ./
cp -ru $HOME/.config/gitui ./
cp -ru $HOME/.config/greenclip.toml ./
cp -ru $HOME/.config/gtk-2.0 ./
cp -ru $HOME/.config/gtk-3.0 ./
cp -ru $HOME/.config/gtk-4.0 ./
cp -ru $HOME/.config/helix ./
cp -ru $HOME/.config/htop ./
cp -ru $HOME/.config/hypr ./
cp -ru $HOME/.config/i3 ./
cp -ru $HOME/.config/i3status ./
cp -ru $HOME/.config/kitty ./
cp -ru $HOME/.config/luakit ./
cp -ru $HOME/.config/lvim ./
cp -ru $HOME/.config/mako./
cp -ru $HOME/.config/mpd ./
cp -ru $HOME/.config/mpdris2 ./
cp -ru $HOME/.config/mpv ./
cp -ru $HOME/.config/ncmpcpp/ ./
cp -ru $HOME/.config/neofetch ./
cp -ru $HOME/.config/networkmanager-dmenu ./
cp -ru $HOME/.config/nnn ./
cp -ru $HOME/.config/nvim ./
cp -ru $HOME/.config/papis ./
cp -ru $HOME/.config/ranger ./
cp -ru $HOME/.config/rbw ./
cp -ru $HOME/.config/rofi ./
cp -ru $HOME/.config/safeeyes ./
cp -ru $HOME/.config/sioyek ./
cp -ru $HOME/.config/sway ./
cp -ru $HOME/.config/swaylock ./
cp -ru $HOME/.config/systemd ./
cp -ru $HOME/.local/share/themes ./
cp -ru $HOME/.config/.ticker.yaml ./
cp -ru $HOME/.config/tickrs ./
cp -ru $HOME/.config/tridactyl ./
cp -ru $HOME/.config/userscripts/ ./
cp -ru $HOME/.config/uncrustify ./
cp -ru $HOME/.config/waybar ./
cp -ru $HOME/.config/wezterm ./
cp -ru $HOME/.config/wireplumber ./
cp -ru $HOME/.config/wofi ./
cp -ru $HOME/.config/yay ./
cp -ru $HOME/.config/yazi ./
cp -ru $HOME/.config/zathura ./
cp -u $HOME/.mozilla/firefox/*default-release/chrome/userChrome.css ./
cp -u $HOME/.waterfox/4x08ji4q.default-release/chrome/userChrome.css waterfox-chrome.css
cp -u $HOME/.bashrc ./
cp -u $HOME/.p10k.zsh ./
cp -u $HOME/.vimrc ./
cp -u $HOME/.zshrc ./

