theme = "tokyonight"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
max-depth = 3

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.soft-wrap]
enable = true