preload = /home/joel/.config/userscripts/walls/kurzgesagt/day.jpg
preload = /home/joel/.config/userscripts/walls/kurzgesagt/night.jpg

wallpaper = HDMI-A-1,/home/joel/.config/userscripts/walls/kurzgesagt/day.jpg

ipc = off
splash = true
